services:
  postgres:
    image: postgres
    container_name: postgres_db_container
    environment:
      - POSTGRES_DB=${POSTGRES_DB:-postgres}
      - POSTGRES_USER=${POSTGRES_USER:-postgres}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:-password123}
    ports:
      - "2345:5432"
    restart: unless-stopped

  app:
    container_name: app_container
    build: .
    ports:
      - "3000:3000"
    depends_on:
      - postgres
